--This is a bootstrap file. It must be run manually. Adjust the setting in it accordingly. All other schema
-- will be updated automatically whenever a new war is deployed

CREATE DATABASE [BigSense] 
GO
ALTER DATABASE [BigSense] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [BigSense] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BigSense] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BigSense] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BigSense] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BigSense] SET ARITHABORT OFF 
GO
ALTER DATABASE [BigSense] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BigSense] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BigSense] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BigSense] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BigSense] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BigSense] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BigSense] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BigSense] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BigSense] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BigSense] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BigSense] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BigSense] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BigSense] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BigSense] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BigSense] SET  READ_WRITE 
GO
ALTER DATABASE [BigSense] SET RECOVERY FULL 
GO
ALTER DATABASE [BigSense] SET  MULTI_USER 
GO
ALTER DATABASE [BigSense] SET PAGE_VERIFY CHECKSUM  
GO
USE [BigSense]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [BigSense] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

--Create DBO User

USE [BigSense]
GO
CREATE LOGIN [db_bigsense_ddl] WITH PASSWORD=N'insertpassword', DEFAULT_DATABASE=[BigSense], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--Add DBO Role to Insrance

USE [BigSense]
GO
CREATE USER [db_bigsense_ddl] FOR LOGIN [db_bigsense_ddl]
GO
USE [BigSense]
GO
EXEC sp_addrolemember N'db_owner', N'db_bigsense_ddl'
GO

--Create Standard User

USE [BigSense]
GO
CREATE LOGIN [db_bigsense] WITH PASSWORD=N'insertpassword', DEFAULT_DATABASE=[BigSense], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [BigSense]
GO
CREATE USER [db_bigsense] FOR LOGIN [db_bigsense]
GO
USE [BigSense]
GO
USE [BigSense]
GO
EXEC sp_addrolemember N'db_datareader', N'db_bigsense'
EXEC sp_addrolemember N'db_datawriter', N'db_bigsense'
GO
GO


CREATE TABLE ddl_info (
	id BIGINT IDENTITY(1,1) PRIMARY KEY,
	version INT,
	installed rowversion
);
